### ISSUE TITLE
error: Usage of `--profile` requires `-Z unstable-options`

### ISSUE THREAD

**Issue by coffeepotkiller** [system76/thelio-io-windows#22]
I compiled and installed this within my Windows partition on my Thelio Mira r1 about two years ago without issue.

However, today I had to reinstall my Windows OS and when trying to set this up again I'm running into this error at the `python build.py` step:

```
error: Usage of `--profile` requires `-Z unstable-options`
Error[1] (Command): The 'cargo' application failed with exit code = 101
Traceback (most recent call last):
File "C:\Users\grizzle\Desktop\thelio\build.py", line 16, in <module>
subprocess.check_call([
File "C:\Python312\Lib\subprocess.py", line 413, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cargo', 'wix', '--nocapture', '--verbose']' returned non-zero exit status 1.
```

I searched through all the source files in this repo but I can't find any mention of the `--profile` argument where I could try to manually add `-Z unstable-options`. I don't know anything about Rust though...

**Comment by jackpot51** [comment]
Which version of rust are you using?

**Comment by coffeepotkiller** [comment]
> Which version of rust are you using?

Looks to be: `rustc 1.75.0 (82e1608df 2023-12-21)`

**Comment by jackpot51** [comment]
Can you try running `cargo install -f cargo-wix`?

**Comment by coffeepotkiller** [comment]
> Can you try running `cargo install -f cargo-wix`?

I tried that, no change!

```
C:\Users\grizzle>cargo install -f cargo-wix
    Updating crates.io index
  Installing cargo-wix v0.3.8
    Updating crates.io index
   Compiling proc-macro2 v1.0.76
   Compiling unicode-ident v1.0.12
   Compiling windows_x86_64_msvc v0.52.0
   Compiling serde v1.0.195
   Compiling winapi v0.3.9
   Compiling thiserror v1.0.56
   Compiling autocfg v1.1.0
   Compiling windows_x86_64_msvc v0.48.5
   Compiling utf8parse v0.2.1
   Compiling memchr v2.7.1
   Compiling anstyle v1.0.4
   Compiling cfg-if v1.0.0
   Compiling anstyle-parse v0.2.3
   Compiling camino v1.1.6
   Compiling semver v1.0.21
   Compiling log v0.4.20
   Compiling serde_json v1.0.111
   Compiling num-traits v0.2.17
   Compiling aho-corasick v1.1.2
   Compiling colorchoice v1.0.0
   Compiling regex-syntax v0.8.2
   Compiling itoa v1.0.10
   Compiling peresil v0.3.0
   Compiling clap_lex v0.6.0
   Compiling windows-targets v0.52.0
   Compiling strsim v0.10.0
   Compiling ryu v1.0.16
   Compiling windows-sys v0.52.0
   Compiling typed-arena v1.7.0
   Compiling windows-targets v0.48.5
   Compiling sxd-document v0.3.2
   Compiling log v0.3.9
   Compiling quote v1.0.35
   Compiling getrandom v0.2.12
   Compiling encoding_rs v0.8.33
   Compiling syn v2.0.48
   Compiling quick-error v1.2.3
   Compiling either v1.9.0
   Compiling humantime v2.1.0
   Compiling uuid v1.6.1
   Compiling sxd-xpath v0.4.2
   Compiling anstyle-query v1.0.2
   Compiling anstyle-wincon v3.0.2
   Compiling is-terminal v0.4.10
   Compiling anstream v0.6.11
   Compiling chrono v0.4.31
   Compiling itertools v0.11.0
   Compiling clap_builder v4.4.18
   Compiling regex-automata v0.4.3
   Compiling lazy_static v1.4.0
   Compiling winapi-util v0.1.6
   Compiling termcolor v1.4.1
   Compiling encoding_rs_io v0.1.7
   Compiling serde_derive v1.0.195
   Compiling thiserror-impl v1.0.56
   Compiling regex v1.10.2
   Compiling clap v4.4.18
   Compiling rustc-cfg v0.5.0
   Compiling env_logger v0.10.2
   Compiling cargo-platform v0.1.6
   Compiling mustache v0.9.0
   Compiling cargo_metadata v0.18.1
   Compiling cargo-wix v0.3.8
    Finished release [optimized] target(s) in 22.49s
   Replacing C:\Users\grizzle\.cargo\bin\cargo-wix.exe
    Replaced package `cargo-wix v0.3.8` with `cargo-wix v0.3.8` (executable `cargo-wix.exe`)


C:\Users\grizzle\Desktop\thelio>python build.py
 INFO: Building the binary
error: Usage of `--profile` requires `-Z unstable-options`
Error[1] (Command): The 'cargo' application failed with exit code = 101
Traceback (most recent call last):
  File "C:\Users\grizzle\Desktop\thelio\build.py", line 16, in <module>
    subprocess.check_call([
  File "C:\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cargo', 'wix', '--nocapture', '--verbose']' returned non-zero exit status 1.

C:\Users\grizzle\Desktop\thelio>


```

**Comment by ids1024** [comment]
Looks like https://github.com/system76/thelio-io-windows/blob/master/rust-toolchain specifies 1.53.0, while --profile was stabilized in 1.57.0.

So the version in `rust-toolchain` needs to be bumped to something newer.

**Comment by coffeepotkiller** [comment]
> Looks like https://github.com/system76/thelio-io-windows/blob/master/rust-toolchain specifies 1.53.0, while --profile was stabilized in 1.57.0.
> 
> So the version in `rust-toolchain` needs to be bumped to something newer.

That fixed it for me!! I updated my local rust-toolchain file to 1.57.0 and I was then able to build the MSI and install it. I can now take my noise cancelling headphones off :-)

@jackpot51 @ids1024 thank you so much....I'm immensely appreciative how quickly you both jumped in here to help
