### ISSUE TITLE
Windows 11 Support?

### ISSUE THREAD

**Issue by ghost** [system76/thelio-io-windows#8]
I just installed Windows 11 on my Thelio Mira and I was trying to build this installer for fan control but I got the following error on the `python build.py` step.  Not sure if this is related to Windows 11 vs 10 or if there's something else that I'm doing wrong?

```
C:\Users\gregg\Downloads\thelio-io-windows-master\thelio-io-windows-master>python build.py
info: syncing channel updates for '1.50.0-x86_64-pc-windows-msvc'
info: latest update on 2021-02-11, rust version 1.50.0 (cb75ad5db 2021-02-10)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
 INFO: Building the release binary
    Updating crates.io index
  Downloaded bitflags v1.2.1
  Downloaded proc-macro-error-attr v1.0.4
  Downloaded serde v1.0.125
  Downloaded quote v1.0.9
  Downloaded widestring v0.4.3
  Downloaded block-buffer v0.7.3
  Downloaded generic-array v0.12.4
  Downloaded err-derive v0.2.4
  Downloaded opaque-debug v0.2.3
  Downloaded byte-tools v0.3.1
  Downloaded sha2 v0.8.2
  Downloaded regex v1.5.3
  Downloaded winlog v0.2.6
  Downloaded unicode-xid v0.2.2
  Downloaded windows-service v0.3.1
  Downloaded memchr v2.4.0
  Downloaded libc v0.2.94
  Downloaded synstructure v0.12.4
  Downloaded digest v0.8.1
  Downloaded winreg v0.5.1
  Downloaded proc-macro-error v1.0.4
  Downloaded winres v0.1.11
  Downloaded unicode-width v0.1.8
  Downloaded syn v1.0.72
  Downloaded getopts v0.2.21
  Downloaded proc-macro2 v1.0.26
  Downloaded byteorder v1.4.3
  Downloaded rustversion v1.0.5
  Downloaded typenum v1.13.0
  Downloaded block-padding v0.1.5
  Downloaded version_check v0.9.3
  Downloaded serialport v4.0.1
  Downloaded fake-simd v0.1.2
  Downloaded smbios-lib v0.7.3
  Downloaded 34 crates (1.8 MB) in 1.42s
   Compiling memchr v2.4.0
   Compiling proc-macro2 v1.0.26
   Compiling typenum v1.13.0
   Compiling unicode-xid v0.2.2
   Compiling version_check v0.9.3
   Compiling syn v1.0.72
   Compiling rustversion v1.0.5
   Compiling winapi v0.3.9
   Compiling byte-tools v0.3.1
   Compiling serde v1.0.125
   Compiling byteorder v1.4.3
   Compiling regex-syntax v0.6.25
   Compiling opaque-debug v0.2.3
   Compiling fake-simd v0.1.2
   Compiling log v0.4.14
   Compiling libc v0.2.94
   Compiling bitflags v1.2.1
   Compiling cfg-if v1.0.0
   Compiling unicode-width v0.1.8
   Compiling widestring v0.4.3
   Compiling block-padding v0.1.5
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling getopts v0.2.21
   Compiling smbios-lib v0.7.3
   Compiling aho-corasick v0.7.18
   Compiling quote v1.0.9
   Compiling err-derive v0.2.4
   Compiling generic-array v0.12.4
   Compiling regex v1.5.3
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling sha2 v0.8.2
   Compiling toml v0.5.8
   Compiling synstructure v0.12.4
   Compiling winlog v0.2.6
   Compiling winres v0.1.11
   Compiling winreg v0.5.1
   Compiling serialport v4.0.1
   Compiling thelio-io v0.1.0 (C:\Users\gregg\Downloads\thelio-io-windows-master\thelio-io-windows-master)
error: failed to run custom build command for `thelio-io v0.1.0 (C:\Users\gregg\Downloads\thelio-io-windows-master\thelio-io-windows-master)`

Caused by:
  process didn't exit successfully: `C:\Users\gregg\Downloads\thelio-io-windows-master\thelio-io-windows-master\target\release\build\thelio-io-c6756d07f2d84094\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=app.manifest
  package.metadata does not exist
  "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.19041.0\\x64\\rc.exe"
  RC Output:
  Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
  Copyright (C) Microsoft Corporation.  All rights reserved.


  ------
  RC Error:

  ------
  cargo:rustc-link-search=native=C:\Users\gregg\Downloads\thelio-io-windows-master\thelio-io-windows-master\target\release\build\thelio-io-b6607f9a57c3b563\out
  cargo:rustc-link-lib=dylib=resource
  cargo:rerun-if-changed=wrapper/Program.cs
  cargo:rerun-if-changed=wrapper/wrapper.csproj

  --- stderr
  Could not execute because the application was not found or a compatible .NET SDK is not installed.
  Possible reasons for this include:
    * You intended to execute a .NET program:
        The application 'build' does not exist.
    * You intended to execute a .NET SDK command:
        It was not possible to find any installed .NET SDKs.
        Install a .NET SDK from:
          https://aka.ms/dotnet-download
  thread 'main' panicked at 'failed to build wrapper: exit code: 0x80008091', build.rs:21:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Error[1] (Command): The 'cargo' application failed with exit code = 101
Traceback (most recent call last):
  File "C:\Users\gregg\Downloads\thelio-io-windows-master\thelio-io-windows-master\build.py", line 16, in <module>
    subprocess.check_call([
  File "C:\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cargo', 'wix', '--nocapture', '--verbose']' returned non-zero exit status 1.

C:\Users\gregg\Downloads\thelio-io-windows-master\thelio-io-windows-master>
```

**Comment by jackpot51** [comment]
Windows 11 is supported but you will need to install the .NET SDK as you are directed to by the error message.

**Comment by ghost** [comment]
Thanks so much @jackpot51 ! I'm not a developer so appreciate the tip, should have caught that obvious error in hindsight.  I installed .NET SDK and got past that error.

On my latest build attempts I now get `MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. ` errors but I think this is due to me not correctly cloning with Git LFS since some sample DLL files are ~1KB instead of ~300KB.  Going to try to read about Git LFS further and see if I can figure that out.

**Comment by ghost** [comment]
Correctly cloned repo with GIT LFS, successfully built MSI, installed and then.....the sweet sweet silence of fans not running at 100% :-) 

Thanks again @jackpot51!

**Comment by jackpot51** [comment]
That's awesome! I do hope to release the software sometime soon. The major issue is that the error handling right now will quit the daemon instead of try to restart it.

**Comment by ghost** [comment]
I put an additional hard drive in my Thelio Mira and installed Windows 11 to run some apps (...Halo Infinite).  If there's anything I can help with testing the upcoming software release please do let me know!
